id = "zlang"
name = "Zlang"
version = "0.1.1"
schema_version = 1
authors = ["zlangdevs"]
description = "Zlang syntax highlighting for Zed"
repository = "https://github.com/zlangdevs/zed-zlang"

[grammars.zlang]
repository = "https://github.com/zlangdevs/zed-zlang"
rev = "000082a0332ce84899d76cf054180fddac992c07"
