id = "zlang"
name = "Zlang"
version = "0.1.2"
schema_version = 1
authors = ["zlangdevs"]
description = "Zlang syntax highlighting for Zed"
repository = "https://github.com/zlangdevs/zed-zlang"

[grammars.zlang]
repository = "https://github.com/zlangdevs/zed-zlang"
rev = "7dc4cbf7f24f6c741e53b05ed48e41d712679751"
