id = "zlang"
name = "Zlang"
version = "0.1.1"
schema_version = 1
authors = ["zlangdevs"]
description = "Zlang syntax highlighting for Zed"
repository = "https://github.com/zlangdevs/zed-zlang"

[grammars.zlang]
repository = "https://github.com/zlangdevs/zed-zlang"
rev = "47d7c7f0d41ec262ca8d66a61412d3076e62850f"
